In [1]:
from rocketml.ensemble import GradientBoostingClassifier
from rocketml.io import LIBSVM,CSV
from time import time
import bokeh
import subprocess
import os
from glob import glob
from sklearn.metrics import f1_score, confusion_matrix,roc_auc_score
from sklearn.datasets import load_svmlight_file
import numpy as np

## Start dask for data processing

In [2]:
hostname = subprocess.check_output('hostname').strip()
from dask.distributed import Client
client = Client(hostname+":8786")
client

<Client: scheduler='tcp://172.31.17.80:8786' processes=4 cores=64>

## Read Data File and Inspect its contents

In [36]:
import dask.dataframe as dd
filename = "s3://nyc-tlc/trip+data/yellow_tripdata_2017-01.csv"
df = dd.read_csv(filename,header=None)

## Check data statistics

In [37]:
print(df.columns)
print(df.head())
stats = df.describe()
print(stats.compute())

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
            17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
           dtype='int64')
    0         1         2         3         4         5         6         7   \
0  1.0  0.869293 -0.635082  0.225690  0.327470 -0.689993  0.754202 -0.248573   
1  1.0  0.907542  0.329147  0.359412  1.497970 -0.313010  1.095531 -0.557525   
2  1.0  0.798835  1.470639 -1.635975  0.453773  0.425629  1.104875  1.282322   
3  0.0  1.344385 -0.876626  0.935913  1.992050  0.882454  1.786066 -1.646778   
4  1.0  1.105009  0.321356  1.522401  0.882808 -1.205349  0.681466 -1.070464   

         8         9     ...           19        20        21        22  \
0 -1.092064  0.000000    ...    -0.010455 -0.045767  3.101961  1.353760   
1 -1.588230  2.173076    ...    -1.138930 -0.000819  0.000000  0.302220   
2  1.381664  0.000000    ...     1.128848  0.900461  0.000000  0.909753   
3 -0.942383  0.000000    ...    -0.678379 -1.360356 

In [42]:
rows = df[0].count().compute()
print(rows)

11000000


## Create test and train data for Gradient Boosted Trees

In [120]:
df_train,df_test = df.random_split([0.95,0.05])

In [121]:
df_train.compute()
df_test.compute()

0         1         2         3         4         5         6   \
29     0.0  1.250867 -0.750010  1.090164  0.461849 -0.380657  0.677161   
104    0.0  1.177847 -1.467825 -0.930746  1.112738  0.176547  0.710414   
120    1.0  0.817685 -0.867860  0.518657  0.705481  0.775555  1.202070   
129    1.0  1.215180  0.744058  0.536967  0.533705 -1.341770  1.030856   
148    0.0  1.974485 -0.520153 -0.273788  1.046293 -0.317087  1.239995   
151    1.0  1.031805 -0.977919  0.677902  0.603602 -1.026682  0.742843   
154    0.0  1.212435  0.265839  0.342211  0.967790  0.933620  0.797532   
162    0.0  0.871855  0.716787  1.067415  0.424898 -1.152868  0.856344   
222    0.0  2.057571  0.190844  1.474128  0.653487 -0.063609  0.813930   
232    1.0  0.586361 -1.273031  1.393673  0.039736  0.717229  0.991557   
244    0.0  0.301050 -0.435418  1.175613  2.127683 -1.580217  1.008870   
263    0.0  0.670728 -1.475617 -1.488937  1.632550 -0.633338  0.479014   
297    1.0  0.620950 -1.015903  0.577472  0.776368 -0.342783  0.619082   
335    0.0  1.323888  0.518097 -1.577714  0.692344 -0.547747  0.972869   
338    0.0  1.436438  0.263891 -0.970141  1.420141 -0.438603  1.126677   
386    0.0  0.450568  1.023587 -1.244798  0.855013  0.187299  0.460876   
409    1.0  1.305404  1.039171  1.572894  1.512336 -1.052484  0.812464   
462    0.0  2.060499  0.441154  0.341656  0.723234 -0.459829  1.045330   
481    1.0  1.062734  1.222277  0.545845  1.182560  1.151183  1.248423   
515    1.0  1.042969 -0.498726  1.051879  0.745844  0.285480  0.667450   
526    1.0  1.057060 -0.750010 -1.237584  1.709434  1.551741  0.722689   
532    0.0  1.192121 -0.449054 -1.693126  1.263792 -1.267288  1.166068   
537    1.0  1.190840  0.988524  0.518102  1.175757  1.150089  0.412691   
543    1.0  1.001975  0.493748  0.150784  1.539349  0.876077  1.007038   
551    1.0  1.090917  1.279741  1.623941  1.175250 -1.139165  0.950883   
559    1.0  1.436072  0.204479  0.465945  1.120703  1.170869  1.135746   
568    0.0  1.609382 -0.811370 -1.613780  0.526785 -0.439796  0.894086   
595    0.0  0.412503  0.291162  0.041476  1.193014 -0.365972  0.434035   
608    1.0  1.570584  0.859960 -1.020079  1.754266  1.663192  1.192726   
612    0.0  0.816404 -0.033169  1.173948  0.643212  1.055455  1.186680   
...    ...       ...       ...       ...       ...       ...       ...   
47862  1.0  0.917608  1.577775 -0.257142  0.772908 -1.689542  0.312289   
47867  1.0  0.860143  1.389799 -1.680919  1.249081 -1.085751  1.553109   
47883  1.0  0.310383 -0.078946  0.038147  0.441723 -0.378617  1.764905   
47904  1.0  0.689761 -0.499700 -0.285440  1.552419 -1.457000  0.753653   
47917  1.0  0.860509  0.533681 -1.179324  0.764948  0.043851  0.850756   
47948  1.0  0.838914 -0.485091  1.522401  0.496875  0.296581  1.705910   
47989  0.0  0.736063  1.270975  1.694408  1.223635 -0.732790  0.933386   
48013  1.0  1.675997 -0.627290 -0.334267  0.555448  0.094595  0.709131   
48032  0.0  0.552687 -0.602941  1.226105  1.666057 -0.791737  1.826923   
48054  0.0  0.790965 -1.861308 -1.546087  0.615508  0.481018  0.851123   
48056  1.0  1.177297  0.933008  0.261201  0.706512 -0.962484  0.748614   
48087  1.0  1.016067 -1.647035  0.849909  0.613611 -1.530960  0.809533   
48089  0.0  0.843306 -0.262052  0.246775  0.617427 -1.200893  1.080965   
48094  0.0  1.092015  1.450185  0.648495  0.973229 -0.772217  0.437699   
48099  0.0  0.560740 -0.760724  0.875988  1.521625  0.009291  0.569156   
48122  1.0  0.721971 -0.686702 -1.093875  1.122886 -0.979767  0.564484   
48141  1.0  0.448921  0.110004  0.773338  1.817213  1.223827  0.982396   
48202  0.0  1.157899  1.272923 -0.608372  1.727724 -0.199922  1.275447   
48283  1.0  0.816404  0.275579  0.132474  1.732036  0.853256  0.454280   
48296  1.0  1.031073 -0.888314 -0.378656  0.418909  0.700501  0.566407   
48311  1.0  0.555616 -1.131806  0.556942  1.277497  1.318034  1.026276   
48323  1.0  1.712599 -0.157837  0.502566  0.795081  0.774878  0.610470   
48399  0.0  

In [122]:
df_test.to_csv("/shared/data/test_data/",header=None,index=False)

['/shared/data/test_data/000.part',
 '/shared/data/test_data/001.part',
 '/shared/data/test_data/002.part',
 '/shared/data/test_data/003.part',
 '/shared/data/test_data/004.part',
 '/shared/data/test_data/005.part',
 '/shared/data/test_data/006.part',
 '/shared/data/test_data/007.part',
 '/shared/data/test_data/008.part',
 '/shared/data/test_data/009.part',
 '/shared/data/test_data/010.part',
 '/shared/data/test_data/011.part',
 '/shared/data/test_data/012.part',
 '/shared/data/test_data/013.part',
 '/shared/data/test_data/014.part',
 '/shared/data/test_data/015.part',
 '/shared/data/test_data/016.part',
 '/shared/data/test_data/017.part',
 '/shared/data/test_data/018.part',
 '/shared/data/test_data/019.part',
 '/shared/data/test_data/020.part',
 '/shared/data/test_data/021.part',
 '/shared/data/test_data/022.part',
 '/shared/data/test_data/023.part',
 '/shared/data/test_data/024.part',
 '/shared/data/test_data/025.part',
 '/shared/data/test_data/026.part',
 '/shared/data/test_data/027

In [123]:
test_filenames = glob('/shared/data/test_data/*.part')
with open('/shared/data/test.csv','w') as fp:
    for fn in test_filenames:
        with open(fn) as f:
            fp.write(f.read())

In [124]:
df_train.to_csv('/shared/data/train_data/',header=None,index=False)

['/shared/data/train_data/000.part',
 '/shared/data/train_data/001.part',
 '/shared/data/train_data/002.part',
 '/shared/data/train_data/003.part',
 '/shared/data/train_data/004.part',
 '/shared/data/train_data/005.part',
 '/shared/data/train_data/006.part',
 '/shared/data/train_data/007.part',
 '/shared/data/train_data/008.part',
 '/shared/data/train_data/009.part',
 '/shared/data/train_data/010.part',
 '/shared/data/train_data/011.part',
 '/shared/data/train_data/012.part',
 '/shared/data/train_data/013.part',
 '/shared/data/train_data/014.part',
 '/shared/data/train_data/015.part',
 '/shared/data/train_data/016.part',
 '/shared/data/train_data/017.part',
 '/shared/data/train_data/018.part',
 '/shared/data/train_data/019.part',
 '/shared/data/train_data/020.part',
 '/shared/data/train_data/021.part',
 '/shared/data/train_data/022.part',
 '/shared/data/train_data/023.part',
 '/shared/data/train_data/024.part',
 '/shared/data/train_data/025.part',
 '/shared/data/train_data/026.part',
 

In [125]:
train_filenames = glob('/shared/data/train_data/*.part')
with open('/shared/data/train.csv','w') as fp:
    for fn in train_filenames:
        with open(fn) as f:
            fp.write(f.read())

In [ ]:
start = time()
data_file = LIBSVM(filename='/home/ubuntu/rocketml-dev/data/avazu-app.tr')
gbdt_classifier = GradientBoostingClassifier(n_estimators=100,learning_rate=0.1,num_leaves=255,min_child_samples=0,min_sum_hessian_in_leaf=100,tree_learner="voting")
gbdt_classifier.fit(data_file)
print("Time to build a model = %0.2f"%(time()-start))
test_file_name = '/home/ubuntu/rocketml-dev/data/avazu-app.val'
test_file = LIBSVM(filename=test_file_name)
y_predict = gbdt_classifier.predict(test_file)
_,y_true = load_svmlight_file(test_file_name)
f1 = f1_score(y_true,y_predict)
cm = confusion_matrix(y_true,y_predict)
print("F1 score = %0.2f"%f1)
print("Confusion matrix")
print(cm)

------------------
Cluster Resources
------------------
Nodes        = 4
Sockets/node = 1
Cores/socket = 8
--------------------------
Total Cores    = 32
Total Memory(GB)   = 121.68
--------------------------


In [3]:
gbdt_classifier.feature_importance()

array([0, 0, 0, ..., 0, 0, 0])

In [16]:
test_file = LIBSVM(filename='/home/ubuntu/rocketml-dev/data/avazu-app.val')
y_predict = gbdt_classifier.predict(test_file)

------------------
Cluster Resources
------------------
Nodes        = 4
Sockets/node = 1
Cores/socket = 8
--------------------------
Total Cores    = 32
Total Memory(GB)   = 121.68
--------------------------


In [18]:
y_true

array([1., 1., 0., ..., 0., 0., 1.])

In [15]:
np.argwhere(y_true < 0.)

array([], shape=(0, 1), dtype=int64)

In [20]:
print(cm)

[[1697067    3895]
 [ 246726    6263]]


In [22]:
y_predict

array([0, 0, 0, ..., 0, 0, 0])